/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_api_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assess */
        post: operations["assess_api_assess_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Countries
         * @description Coverage + last-reviewed date per country, so a client never hardcodes
         *     what the knowledge base actually contains (docs/04-FRONTEND-DESIGN.md #7.5).
         */
        get: operations["list_countries_api_countries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/countries/{code}/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Country Rules
         * @description Every rule for one country, unfiltered by any business profile.
         *
         *     Deliberately not rate-limited alongside /api/ask and /api/assess: this
         *     is a plain SELECT with no LLM call behind it, so it costs nothing to
         *     serve and the intake preview can fire it on every country click.
         */
        get: operations["country_rules_api_countries__code__rules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AskRequest */
        AskRequest: {
            /** Country */
            country: string;
            /** Question */
            question: string;
        };
        /** AskResponse */
        AskResponse: {
            /** Answer */
            answer: string;
            /** Citations */
            citations: string[];
            /** Refused */
            refused: boolean;
        };
        /** AssessRequest */
        AssessRequest: {
            /** Country */
            country: string;
            /** Vat Registered */
            vat_registered: boolean;
            /** Employee Count */
            employee_count: number;
            /** Annual Turnover Eur */
            annual_turnover_eur?: number | null;
            /** Invoices To */
            invoices_to: string[];
        };
        /** AssessResponse */
        AssessResponse: {
            /** In Scope */
            in_scope: boolean;
            /** Obligations */
            obligations: components["schemas"]["Obligation"][];
            /** Next Steps */
            next_steps: string[];
            /** Disclaimer */
            disclaimer: string;
        };
        /**
         * CountryOut
         * @description What a frontend needs to render country choices without hardcoding coverage.
         */
        CountryOut: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /**
             * Last Reviewed
             * Format: date
             */
            last_reviewed: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Obligation
         * @description One applicable rule, rendered for the API.
         *
         *     Every field except `explanation` is copied verbatim from a `rules` row -
         *     the LLM never decides a date, threshold, format, or network (CLAUDE.md).
         */
        Obligation: {
            /** Rule Type */
            rule_type: string;
            /**
             * Applies From
             * Format: date
             */
            applies_from: string;
            /** Format Required */
            format_required: string | null;
            /** Network */
            network: string | null;
            /** Explanation */
            explanation: string;
            /** Source Url */
            source_url: string;
            /**
             * Source Reviewed At
             * Format: date
             */
            source_reviewed_at: string;
        };
        /**
         * RuleOut
         * @description One `rules` row, verbatim, with no profile applied and no LLM involved.
         *
         *     This is what a country looks like *before* anyone describes their
         *     business - the intake preview (docs/04-FRONTEND-DESIGN.md #3.2) shows
         *     it the moment a country is picked, which is why it must stay free to
         *     serve: no generation, no per-request cost.
         */
        RuleOut: {
            /** Rule Type */
            rule_type: string;
            /**
             * Applies From
             * Format: date
             */
            applies_from: string;
            /** Format Required */
            format_required: string | null;
            /** Network */
            network: string | null;
            /** Penalty Summary */
            penalty_summary: string | null;
            /** Source Url */
            source_url: string;
            /**
             * Source Reviewed At
             * Format: date
             */
            source_reviewed_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ask_api_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assess_api_assess_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssessRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_countries_api_countries_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountryOut"][];
                };
            };
        };
    };
    country_rules_api_countries__code__rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
