"""initial schema

Revision ID: c3b2e46adefc
Revises:
Create Date: 2026-09-03 13:16:22.413268

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        "countries",
        sa.Column("code", sa.CHAR(length=2), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("last_reviewed", sa.Date(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "query_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("endpoint", sa.Text(), nullable=True),
        sa.Column("request_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("retrieved_ids", postgresql.ARRAY(sa.Integer()), nullable=True),
        sa.Column("response_text", sa.Text(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("refused", sa.Boolean(), server_default=sa.text("false"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rule_chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("country_code", sa.CHAR(length=2), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
        sa.ForeignKeyConstraint(
            ["country_code"],
            ["countries.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("country_code", sa.CHAR(length=2), nullable=True),
        sa.Column("rule_type", sa.Text(), nullable=False),
        sa.Column("applies_from", sa.Date(), nullable=False),
        sa.Column("applies_to_segment", sa.Text(), nullable=False),
        sa.Column("threshold_amount", sa.Numeric(), nullable=True),
        sa.Column("threshold_currency", sa.CHAR(length=3), nullable=True),
        sa.Column("format_required", sa.Text(), nullable=True),
        sa.Column("network", sa.Text(), nullable=True),
        sa.Column("penalty_summary", sa.Text(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("source_reviewed_at", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["country_code"],
            ["countries.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rules")
    op.drop_table("rule_chunks")
    op.drop_table("query_logs")
    op.drop_table("countries")
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS vector")
